### PR TITLE
Add multi-engine support for fixed length files

### PR DESCRIPTION
**Pull request by petersondrew**
This PR satisfies #10 by adding support for instantiating an engine with multiple layout descriptors or record types.

### CODE REVIEW

**Comment by forcewake** [comment]
Awesome! :octocat:

> to use the Activator to create an instance

Do you check performance? It seemed that it is better to use expressions. More information on the [stackoverflow](http://stackoverflow.com/q/6582259/2688578)

**Comment by petersondrew** [comment]
It appears that you edited your comment regarding performance, but I'll answer it anyway :wink:.

It appears the compiled lambda method only works when the type is known at compile time, rather than runtime. That being said, it may be worth investigating any improvements that can be found over calling `Activator.CreateInstance`. It may be possible to cache new instances per type, we would just need to modify a copy of each new instance to avoid polluting our cached instance (which could end up being more cpu intensive than using the activator, I can't be sure without testing first).

**Comment by petersondrew** [comment]
Actually, I was wrong (as you can easily provide the type as an argument rather than a generic parameter), and I completely missed the implementation you'd already provided!

I've swapped out Activator for your implementation and will be pushing it shortly.

**Comment by forcewake** [comment]
> It appears that you edited your comment regarding performance, but I'll answer it anyway .

I decided that it would be better to make several tests before asking :smile:

**Pull request merged**
