### PR TITLE
Migration to .NET Core

### LINKED ISSUE #55: .Net Core Support
Are there any plans to support .Net Core 1.1/.2.0?

### PR DESCRIPTION
**Pull request by johnnyasantoss**
Fixes #55

### CODE REVIEW

**Comment by johnnyasantoss** [comment]
I've run all the tests in my machine :) everything is working.
The CI script will probably need to have an update.

**Comment by niemyjski** [comment]
Looks like the build is failing, could you make this multi target .net standard 2.0 as well. Also I noticed some of the classes changed / and access modifiers were changed. Can we get the minimal set of changes needed for this to be converted. Otherwise changes look good

**Comment by johnnyasantoss** [comment]
Ahh, I see now why the access modifiers needed to change. I've deleted the assembly attributes `InternalsVisibleTo`.
I'll made some changes to this PR later today. Thanks for reviewing 😄

**Comment by johnnyasantoss** [comment]
Looks like we will have to change the CI build 🤔 

I don't know `psake` and I really think that it is not a good way to do automation scripts.
Would be really nice if we could use [Cake build][cake] - which is really easy to understand and edit since his scripts are plain C#.

EDIT: And cake build is cross-plat too 👍 

 [cake]: https://cakebuild.net/

**Pull request closed without merging**
